/** Fontes oficiais de mapas de referência para o ambiente CAD. */

export {
  ANM_DADOS_ABERTOS_BASE,
  ANM_QUERY_LAYER,
  ANM_SIGMINE_LAYER_ID,
  ANM_SIGMINE_LAYERS,
  ANM_SIGMINE_LAYER_KEYS,
  ANM_SIGMINE_MAPSERVER,
  ANM_SIGMINE_WMS,
  activeAnmMapLayerIds,
  anmQueryLayerUrl,
  anyAnmSigmineOverlay,
  DEFAULT_ANM_SIGMINE_OVERLAY,
  isAnmSigmineLayerKey,
  parseAnmMapLayerIds,
  type AnmSigmineLayerDef,
  type AnmSigmineLayerKey,
  type AnmSigmineOverlayState,
} from "./anm-sigmine-layers";

export {
  DEFAULT_SIGEF_OVERLAY,
  SIGEF_CONSULTA,
  SIGEF_EXTENSAO_OXT,
  SIGEF_I3GEO_OGC,
  SIGEF_LAYER_KEYS,
  SIGEF_LAYERS,
  SIGEF_MODELO_ODS,
  SIGEF_PORTAL,
  SIGEF_UFS,
  activeSigefLayerKeys,
  anySigefOverlay,
  isSigefLayerKey,
  isSigefUf,
  normalizeSigefUf,
  parseSigefMapLayerKeys,
  sigefTema,
  type SigefLayerDef,
  type SigefLayerKey,
  type SigefOverlayState,
  type SigefUf,
} from "./sigef-layers";
